[Icon Theme]
Name=Ubuntu Studio
Comment=Extra icons only Studio uses
Inherits=elementary-xfce-dark

Example=distributor-logo

#Directory list
Directories=places/24,places/48,places/64,places/128,panel/22,apps/48,

[places/24]
Size=24
Context=Status
Type=Fixed

[places/48]
Size=48
Context=Status
Type=Fixed

[places/64]
Size=64
Context=Status
Type=Fixed

[places/128]
Size=128
Context=Status
Type=Fixed

[panel/22]
Size=22
Context=Status
Type=Fixed

[apps/48]
Size=48
Content=Status
Type=Fixed

